### ISSUE TITLE
TypeError: VolumeServer.__init__() missing 1 required positional argument: 'export_uri'

### ISSUE THREAD

**Issue by jonashaag** [scaleway/scaleway-sdk-python#557]
```
ins.get_server(server_id="...", zone="fr-par-2")

File ~/env/lib/python3.10/site-packages/scaleway/instance/v1/api.py:663, in InstanceV1API.get_server(self, server_id, zone)
    657 res = self._request(
    658     "GET",
    659     f"/instance/v1/zones/{param_zone}/servers/{param_server_id}",
    660 )
    662 self._throw_on_error(res)
--> 663 return unmarshal_GetServerResponse(res.json())

File ~/env/lib/python3.10/site-packages/scaleway/instance/v1/marshalling.py:1756, in unmarshal_GetServerResponse(data)
   1754 field = data.get("server", None)
   1755 if field is not None:
-> 1756     args["server"] = unmarshal_Server(field)
   1757 else:
   1758     args["server"] = None

File ~/env/lib/python3.10/site-packages/scaleway/instance/v1/marshalling.py:824, in unmarshal_Server(data)
    821 field = data.get("volumes", None)
    822 if field is not None:
    823     args["volumes"] = (
--> 824         {key: unmarshal_VolumeServer(value) for key, value in field.items()}
    825         if field is not None
    826         else None
    827     )
    829 field = data.get("modification_date", None)
    830 if field is not None:

File ~/env/lib/python3.10/site-packages/scaleway/instance/v1/marshalling.py:824, in <dictcomp>(.0)
    821 field = data.get("volumes", None)
    822 if field is not None:
    823     args["volumes"] = (
--> 824         {key: unmarshal_VolumeServer(value) for key, value in field.items()}
    825         if field is not None
    826         else None
    827     )
    829 field = data.get("modification_date", None)
    830 if field is not None:

File ~/env/lib/python3.10/site-packages/scaleway/instance/v1/marshalling.py:714, in unmarshal_VolumeServer(data)
    711 else:
    712     args["modification_date"] = None
--> 714 return VolumeServer(**args)

TypeError: VolumeServer.__init__() missing 1 required positional argument: 'export_uri'
```

**Comment by otlet** [comment]
I got same problem without reason: no code changes, no updates, nothing.

Example code to reproduce:
```python
from os import getenv
from scaleway import Client
from scaleway.instance.v1 import InstanceV1API

access_key = getenv("SCW_ACCESS_KEY", "")
secret_key = getenv("SCW_SECRET_KEY", "")
client = Client(
    access_key=access_key,
    secret_key=secret_key,
)
api = InstanceV1API(client)
response = api.list_servers(zone="pl-waw-2")
print(response)
```

Error:
```
Traceback (most recent call last):
  File "/home/scaleway/error/inventory.debug.py", line 12, in <module>
    response = api.list_servers(zone="pl-waw-2")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scaleway/.local/share/virtualenvs/ansible-BSRMmTXO/lib/python3.12/site-packages/scaleway/instance/v1/api.py", line 435, in list_servers
    return unmarshal_ListServersResponse(res.json())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scaleway/.local/share/virtualenvs/ansible-BSRMmTXO/lib/python3.12/site-packages/scaleway/instance/v1/marshalling.py", line 2018, in unmarshal_ListServersResponse
    [unmarshal_Server(v) for v in field] if field is not None else None
     ^^^^^^^^^^^^^^^^^^^
  File "/home/scaleway/.local/share/virtualenvs/ansible-BSRMmTXO/lib/python3.12/site-packages/scaleway/instance/v1/marshalling.py", line 823, in unmarshal_Server
    {key: unmarshal_VolumeServer(value) for key, value in field.items()}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scaleway/.local/share/virtualenvs/ansible-BSRMmTXO/lib/python3.12/site-packages/scaleway/instance/v1/marshalling.py", line 713, in unmarshal_VolumeServer
    return VolumeServer(**args)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: VolumeServer.__init__() missing 1 required positional argument: 'export_uri'
```

**Comment by remyleone** [comment]
Hello, do you have any special configuration on your server? Do you have any type of special volume configuration on your side that could us reproduce the issue? At the moment I've tried the following code and it works:

```
from os import getenv
from scaleway import Client
from scaleway.instance.v1 import InstanceV1API

client = Client.from_config_file_and_env()
api = InstanceV1API(client)
response = api.list_servers(zone="pl-waw-2")
print(response)
```

Do you experience the issue on all zones? Which version of the SDK are you using? Have you tried to create a new server and list it? Any snippet of code that we can reproduce goes a long way to help us reproduce the issue.

**Comment by otlet** [comment]
@remyleone no, standard configuration of servers via Terraform. Nothing "special". Block volume + Instance. Zero local volumes.

For reproduce use my project id: `d7770390-8229-4ce0-8151-724277f28ec0`

**Comment by archipell** [comment]
Hello, I am facing the same problem. It seems that the export_uri variable is not mentioned (None) on my volume. The API requires that field to construct VolumeServer, so it is blocking the API response, even if VolumeServer works fine without export_uri. Any luck this will be fixed?

**Comment by otlet** [comment]
@archipell Support promised that they would solve the problem. Unfortunately this is the second time as they say :D

**Comment by Laure-di** [comment]
Hello,

I apologize for the delay; I was away for the past few days. I am currently working on resolving the issue and will keep you updated on the progress.

Thank you so much for your patience.

**Comment by Laure-di** [comment]
The SDK has been released :)

**Comment by otlet** [comment]
I confirm, the SDK has started to work. Thanks!
