### ISSUE TITLE
TypeError on InstanceV1.list_servers

### ISSUE THREAD

**Issue by otlet** [scaleway/scaleway-sdk-python#774]
Example code:
```python
from os import getenv
from scaleway import Client
from scaleway.instance.v1 import InstanceV1API

access_key = getenv("SCW_ACCESS_KEY", "")
secret_key = getenv("SCW_SECRET_KEY", "")
client = Client(
    access_key=access_key,
    secret_key=secret_key,
)
api = InstanceV1API(client)
response = api.list_servers(zone="pl-waw-2")
print(response)
```

Error:
```
Traceback (most recent call last):
  File "/home/otlet/XXX/inventory.debug.py", line 12, in <module>
    response = api.list_servers(zone="pl-waw-2")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/otlet/.local/share/virtualenvs/XXX-XXX/lib/python3.12/site-packages/scaleway/instance/v1/api.py", line 435, in list_servers
    return unmarshal_ListServersResponse(res.json())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/otlet/.local/share/virtualenvs/XXX-XXX/lib/python3.12/site-packages/scaleway/instance/v1/marshalling.py", line 2022, in unmarshal_ListServersResponse
    [unmarshal_Server(v) for v in field] if field is not None else None
     ^^^^^^^^^^^^^^^^^^^
  File "/home/otlet/.local/share/virtualenvs/XXX-XXX/lib/python3.12/site-packages/scaleway/instance/v1/marshalling.py", line 827, in unmarshal_Server
    {key: unmarshal_VolumeServer(value) for key, value in field.items()}
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/otlet/.local/share/virtualenvs/XXX-XXX/lib/python3.12/site-packages/scaleway/instance/v1/marshalling.py", line 715, in unmarshal_VolumeServer
    return VolumeServer(**args)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: VolumeServer.__init__() missing 5 required positional arguments: 'name', 'organization', 'size', 'state', and 'project'
```

Looks like regress with other issue: https://github.com/scaleway/scaleway-sdk-python/issues/557

SDK Version:
```json
        "scaleway": {
            "hashes": [
                "sha256:006a70416f37f9cd8774859a7508cf14af64bc2cb3209a8cff96ddcf48d14627",
                "sha256:745fbd4114caa47d3c6bc5445b8bec5377a93c776ef9984b8741df6749cf519b"
            ],
            "index": "pypi",
            "version": "==2.7.0"
        },
        "scaleway-async": {
            "hashes": [
                "sha256:59d44806ffc2210abd9298b72171e7064779fe1fc67a47bdf13278e66dd52ac0",
                "sha256:9b2cbd9898b92a60debb888529e3506cd4e63369a9ed469fc95a3a674759bfd5"
            ],
            "index": "pypi",
            "version": "==2.7.0"
        },
        "scaleway-core": {
            "hashes": [
                "sha256:1ff173236ffa77239c75942a184d2774c7575d2dbc1303dbb8459a03cf907879",
                "sha256:897b2570fb4a1ab6e4533121ba61cf2d0557d14bd07f9fda68d803b759ae0f11"
            ],
            "markers": "python_version >= '3.8' and python_version < '4.0'",
            "version": "==2.7.0"
        },
```
Python 3.12.2

**Comment by Laure-di** [comment]
Hello,

The issue has been raised to the product team, and a fix should be released at the beginning of January. We apologize for the inconvenience and the delay.

Thank you for reporting this and for your patience.

Laure
